### ISSUE TITLE
LOADays 2020 sponsoring

### ISSUE THREAD

**Issue by toshywoshy** [ota-be/proposals#1]
As per Gratien's request, we hereby invite OTA to sponsor LOADays again.

LOADays is an open source event in Antwerp, Belgium that focuses on system management, operations, development, administration.
The event will take place on 28th and 29th of March 2020, more information on https://loadays.org/2020

Our sponsor document with the levels is available online
https://github.com/loadays/sponsordoc/releases/download/202001/sponsordoc.pdf

We are very happy that you sponsored our previous edition and would appreciate your sponsoring again.

**Comment by gdha** [comment]
@jvanhercke Last year we sponsored LOADays with the 'diamond' level - the same this year?

**Comment by gdha** [comment]
LOADays 2020 was cancelled due to the corona virus outbreak.
