### ISSUE TITLE
Help the students during the Corona crisis [DIgitalForYouth.be]

### ISSUE THREAD

**Issue by gdha** [ota-be/proposals#2]
During the Corona lock-down students have to stay home and need to connect to the school and teachers via a laptop, but unfortunately some children do not have a laptop. There is where DIgitalForYouth.be tries to help - see https://www.digitalforyouth.be/ for more in-depth details.

**Comment by jvanhercke** [comment]
Funds transferred to the Koning Boudewijnstichting
