### ISSUE TITLE
Donatie aan de Warmste Week

### ISSUE THREAD

**Issue by gdha** [ota-be/proposals#4]
https://dewarmsteweek.be/doneer/gegevens - donatie voor de Warmste week?

Dit jaar is het thema '**opgroeien zonder zorgen**' en vlammen we voor een veilige plek voor elk kind en elke jongere.

**Comment by gdha** [comment]
@jvanhercke Doen we eraan mee?

**Comment by jvanhercke** [comment]
@gdha goed voor mij
